### ISSUE TITLE
App crashes everytime I receive a call

### ISSUE THREAD

**Issue by Hirobreak** [mesibo/mesibowebrtcframework#3] opened 2019-03-13 04:27 UTC
Hi, I managed to add `MesiboCall` to my swift project, but now everytime I receive a call my app crashes with the following error: 

```
'*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'***
```

Any thoughts on a reason why this happens?

**Comment by mesibo** [comment] 2019-03-13 04:41
Please post complete logs. You can also try our app on the AppStore or from GitHub link below and see if you are facing the same issue

https://github.com/mesibo/messenger-app-ios

**Comment by Hirobreak** [comment] 2019-03-14 02:11
Here's the complete log:

```
* thread #14, name = 'AVAudioSession Notify Thread', stop reason = signal SIGABRT
  * frame #0: 0x00000001bae93104 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x00000001baf13948 libsystem_pthread.dylib`pthread_kill$VARIANT$armv81 + 296
    frame #2: 0x00000001badead78 libsystem_c.dylib`abort + 140
    frame #3: 0x00000001ba4b4f78 libc++abi.dylib`abort_message + 132
    frame #4: 0x00000001ba4b5120 libc++abi.dylib`default_terminate_handler() + 304
    frame #5: 0x00000001ba4cde58 libobjc.A.dylib`_objc_terminate() + 124
    frame #6: 0x00000001ba4c10fc libc++abi.dylib`std::__terminate(void (*)()) + 16
    frame #7: 0x00000001ba4c1188 libc++abi.dylib`std::terminate() + 84
    frame #8: 0x00000001c120f5d0 AVFAudio`__clang_call_terminate + 12
    frame #9: 0x00000001c129e848 AVFAudio`avfaudio::AVAudioSessionPropertyListener(void*, unsigned int, unsigned int, void const*) + 2796
    frame #10: 0x00000001bf35209c AudioToolbox`AudioSessionPropertyListeners::CallPropertyListenersImp(AudioSessionPropertyListeners const&, unsigned int, unsigned int, void const*) + 796
    frame #11: 0x00000001bf446424 AudioToolbox`AudioSessionPropertyListeners::CallPropertyListeners(unsigned int, unsigned int, void const*) + 224
    frame #12: 0x00000001bf486648 AudioToolbox`HandleCFPropertyListChange(unsigned int, unsigned int, unsigned long, unsigned char*, unsigned int) + 488
    frame #13: 0x00000001bf48b03c AudioToolbox`HandleAudioSessionCFTypePropertyChangedMessage(unsigned int, unsigned int, void*, unsigned int) + 280
    frame #14: 0x00000001bf48a1cc AudioToolbox`ProcessDeferredMessage(unsigned int, __CFData const*, unsigned int, unsigned int) + 1404
    frame #15: 0x00000001bf489920 AudioToolbox`ASCallbackReceiver_AudioSessionPingMessage + 604
    frame #16: 0x00000001bf342908 AudioToolbox`_XAudioSessionPingMessage + 52
    frame #17: 0x00000001bf695190 AudioToolbox`mshMIGPerform + 232
    frame #18: 0x00000001bb28e758 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
    frame #19: 0x00000001bb28dea4 CoreFoundation`__CFRunLoopDoSource1 + 440
    frame #20: 0x00000001bb288c5c CoreFoundation`__CFRunLoopRun + 2140
    frame #21: 0x00000001bb2880e0 CoreFoundation`CFRunLoopRunSpecific + 436
    frame #22: 0x00000001c129c60c AVFAudio`GenericRunLoopThread::Entry(void*) + 164
    frame #23: 0x00000001c12c8768 AVFAudio`CAPThread::Entry(CAPThread*) + 88
    frame #24: 0x00000001baf1825c libsystem_pthread.dylib`_pthread_body + 128
    frame #25: 0x00000001baf181bc libsystem_pthread.dylib`_pthread_start + 48
    frame #26: 0x00000001baf1bcf4 libsystem_pthread.dylib`thread_start + 4
```

**Comment by mesibo** [comment] 2019-03-14 02:31
Thanks, this appears to be a log from the previous version. Are you sure you are using our latest library? Also, can you check if you can reproduce this issue with our App (on AppStore  or the GitHub https://github.com/mesibo/messenger-app-ios )? Since this is not related to webrtc library, can you send us the message on contact@mesibo.com

**Comment by mesibo** [comment] 2019-03-14 08:11
This was happening in the previous version when the phone is in silent. Is that the case?

**Comment by Hirobreak** [comment] 2019-03-18 14:14
Indeed, when I disable silent mode, I'm able to answer calls, Thanks! But now if the other person closes the call, my app crashes with the following:

```
thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x60)
    frame #0: 0x000000010510e69c febo`CAPI::hangup(unsigned int, int) + 72
    frame #1: 0x00000001052653e0 febo`__21-[CallManager hangup]_block_invoke + 140
    frame #2: 0x0000000105120c70 febo`-[Mesibo runInThread:handler:] + 80
    frame #3: 0x000000010526533c febo`-[CallManager hangup] + 168
    frame #4: 0x000000010526010c febo`-[CallInProgressViewController hangup:] + 244
    frame #5: 0x00000001052607f0 febo`-[CallInProgressViewController Mesibo_onCallStatus_uiThread:callid:status:flags:desc:] + 96
    frame #6: 0x00000001227ff824 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #7: 0x0000000122800dc8 libdispatch.dylib`_dispatch_client_callout + 16
    frame #8: 0x000000012280ea78 libdispatch.dylib`_dispatch_main_queue_callback_4CF + 1360
    frame #9: 0x00000001ba9a1ce4 CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
    frame #10: 0x00000001ba99cbac CoreFoundation`__CFRunLoopRun + 1964
    frame #11: 0x00000001ba99c0e0 CoreFoundation`CFRunLoopRunSpecific + 436
    frame #12: 0x00000001bcc15584 GraphicsServices`GSEventRunModal + 100
    frame #13: 0x00000001e7becc00 UIKitCore`UIApplicationMain + 212
  * frame #14: 0x0000000104bd62ac febo`main at AppDelegate.swift:19
    frame #15: 0x00000001ba45abb4 libdyld.dylib`start + 4
```

And this happens with videocalls as well. My Pod.lock shows that webrtc version is 1.0.1, has it been updated for pods?

**Comment by mesibo** [comment] 2019-03-18 14:44
Please update frameworks.

Also, since this question is not related to webrtc framework, I am closing the issue. If you have an issue after update, please email us at contact@mesibo.com

**Closed by mesibo** 2019-03-18 14:44 UTC
